from mesa import Agent
from enum import Enum

# ---------------------------------------------------------------
class Infra(Agent):
    """
    Base class for all infrastructure components

    Attributes
    __________
    vehicle_count : int
        the number of vehicles that are currently in/on (or totally generated/removed by)
        this infrastructure component

    length : float
        the length in meters
    ...

    """

    def __init__(self, unique_id, model, length=0,
                 name='Unknown', road_name='Unknown'):
        super().__init__(unique_id, model)
        self.length = length
        self.name = name
        self.road_name = road_name
        self.vehicle_count = 0

    def step(self):
        pass

    def __str__(self):
        return type(self).__name__ + str(self.unique_id)

# ---------------------------------------------------------------
class Bridge(Infra):
    """
    Creates delay time

    Attributes
    __________
    condition:
        condition of the bridge

    delay_time: int
        the delay (in ticks) caused by this bridge
    ...

    """

    def __init__(self, unique_id, model, length=0,
                 name='Unknown', road_name='Unknown', condition='Unknown', lat=0, lon=0):
        super().__init__(unique_id, model, length, name, road_name)
        self.condition = condition
        self.lat = lat
        self.lon = lon

        self.broken = self.set_broken(self.model.scenario)

    def set_broken(self, rates):
        """
        Determine if the bridge is broken based on its condition and the corresponding probabilities
        """
        broken = False
        cond = str(self.condition).strip().upper()
        if cond in rates:
            rate = rates[cond]
            broken = self.model.random.random() < rate
        
        return broken


    def get_delay_time(self):
        """
        Get the delay time caused by this bridge if it is broken on its condition and length
        """
        if not self.broken:
            self.delay_time = 0
            return self.delay_time
        
        if self.broken:
            if self.length < 10:
                # delay time between 10 and 20 minutes for short bridges
                self.delay_time = self.model.random.uniform(10,20)
            elif self.length < 50:
                # delay time between 15 and 60 minutes for long bridges
                self.delay_time = self.model.random.uniform(15,60)
            elif self.length < 200:
                # delay time between 45 and 90 minutes for very long bridges
                self.delay_time = self.model.random.uniform(45,90)
            else:
                # delay time between 1 and 4 hours for extremely long bridges
                self.delay_time = self.model.random.triangular(60, 120, 240)

        return self.delay_time


# ---------------------------------------------------------------
class Link(Infra):
    pass


# ---------------------------------------------------------------
class Intersection(Infra):
    pass


# ---------------------------------------------------------------
class Sink(Infra):
    """
    Sink removes vehicles

    Attributes
    __________
    vehicle_removed_toggle: bool
        toggles each time when a vehicle is removed
    ...

    """
    vehicle_removed_toggle = False

    def remove(self, vehicle):
        vehicle.removed_at_step = self.model.schedule.steps
        # Record travel time before removing from schedule
        self.model.travel_times.append({
            'vehicle_id': str(vehicle.unique_id),
            'generated_at_step': vehicle.generated_at_step,
            'removed_at_step': vehicle.removed_at_step,
            'travel_time_min': vehicle.removed_at_step - vehicle.generated_at_step,
            'total_delay_time_min': vehicle.delay_time,
            'generated_by': str(vehicle.generated_by),
        })
        self.model.schedule.remove(vehicle)
        self.vehicle_removed_toggle = not self.vehicle_removed_toggle
        # print(str(self) + ' REMOVE ' + str(vehicle))


# ---------------------------------------------------------------
class Source(Infra):
    """
    Source generates vehicles

    Class Attributes:
    -----------------
    truck_counter : int
        the number of trucks generated by ALL sources. Used as Truck ID!

    Attributes
    __________
    generation_frequency: int
        the frequency (the number of ticks) by which a truck is generated

    vehicle_generated_flag: bool
        True when a Truck is generated in this tick; False otherwise
    ...

    """

    truck_counter = 0
    generation_frequency = 5
    vehicle_generated_flag = False

    def step(self):
        if self.model.schedule.steps % self.generation_frequency == 0:
            self.generate_truck()
        else:
            self.vehicle_generated_flag = False

    def generate_truck(self):
        """
        Generates a truck, sets its path, increases the global and local counters
        """
        try:
            agent = Vehicle('Truck' + str(Source.truck_counter), self.model, self)
            if agent:
                self.model.schedule.add(agent)
                agent.set_path()
                if agent.path_ids is None or len(agent.path_ids) == 0:
                    print(f"WARNING: {self} has no valid path, removing truck.")
                    self.model.schedule.remove(agent)
                    return
                Source.truck_counter += 1
                self.vehicle_count += 1
                self.vehicle_generated_flag = True
                # print(str(self) + " GENERATE " + str(agent))
        except Exception as e:
            print("Oops!", e.__class__, e, "occurred.")


# ---------------------------------------------------------------
class SourceSink(Source, Sink):
    """
    Generates and removes trucks
    """
    pass


# ---------------------------------------------------------------
class Vehicle(Agent):
    """

    Attributes
    __________
    speed: float
        speed in meter per minute (m/min)

    step_time: int
        the number of minutes (or seconds) a tick represents
        Used as a base to change unites

    state: Enum (DRIVE | WAIT)
        state of the vehicle

    location: Infra
        reference to the Infra where the vehicle is located

    location_offset: float
        the location offset in meters relative to the starting point of
        the Infra, which has a certain length
        i.e. location_offset < length

    path_ids: Series
        the whole path (origin and destination) where the vehicle shall drive
        It consists the Infras' uniques IDs in a sequential order

    location_index: int
        a pointer to the current Infra in "path_ids" (above)
        i.e. the id of self.location is self.path_ids[self.location_index]

    waiting_time: int
        the time the vehicle needs to wait

    generated_at_step: int
        the timestamp (number of ticks) that the vehicle is generated

    removed_at_step: int
        the timestamp (number of ticks) that the vehicle is removed
    ...
    """

    # 48 km/h translated into meter per min
    speed = 48 * 1000 / 60
    # One tick represents 1 minute
    step_time = 1

    class State(Enum):
        DRIVE = 1
        WAIT = 2

    def __init__(self, unique_id, model, generated_by,
                 location_offset=0, path_ids=None):
        super().__init__(unique_id, model)
        self.generated_by = generated_by
        self.generated_at_step = model.schedule.steps
        self.location = generated_by
        self.location_offset = location_offset
        self.pos = generated_by.pos
        self.path_ids = path_ids
        # default values
        self.state = Vehicle.State.DRIVE
        self.location_index = 0
        self.waiting_time = 0
        self.delay_time = 0
        self.waited_at = None
        self.removed_at_step = None

    def __str__(self):
        return "Vehicle" + str(self.unique_id) + \
               " +" + str(self.generated_at_step) + " -" + str(self.removed_at_step) + \
               " " + str(self.state) + '(' + str(self.waiting_time) + ') ' + \
               str(self.location) + '(' + str(self.location.vehicle_count) + ') ' + str(self.location_offset)

    def set_path(self):
        """
        Set the origin destination path of the vehicle
        """
        self.path_ids = self.model.get_route(self.generated_by.unique_id)

    def step(self):
        """
        Vehicle waits or drives at each step
        """
        if self.state == Vehicle.State.WAIT:
            self.waiting_time = max(self.waiting_time - 1, 0)
            if self.waiting_time == 0:
                self.waited_at = self.location
                self.state = Vehicle.State.DRIVE

        if self.state == Vehicle.State.DRIVE:
            self.drive()

        # print(self)

    def drive(self):
        # the distance that vehicle drives in a tick
        distance = Vehicle.speed * Vehicle.step_time
        distance_rest = self.location_offset + distance - self.location.length

        if distance_rest > 0:
            self.drive_to_next(distance_rest)
        else:
            self.location_offset += distance

    def drive_to_next(self, distance):
        """
        vehicle shall move to the next object with the given distance
        """
        self.location_index += 1

        if self.location_index >= len(self.path_ids):
            print(f"WARNING: {self} reached end of path without a Sink. Removing.")
            self.removed_at_step = self.model.schedule.steps
            self.location.vehicle_count -= 1
            self.model.schedule.remove(self)
            return

        next_id = self.path_ids[self.location_index]
        next_infra = self.model.schedule._agents.get(next_id, None)

        if next_infra is None:
            print(f"ERROR: Agent {next_id} not found in schedule! Removing vehicle.")
            self.removed_at_step = self.model.schedule.steps
            self.location.vehicle_count -= 1
            self.model.schedule.remove(self)
            return

        if isinstance(next_infra, Sink):
            self.arrive_at_next(next_infra, 0)

            # Check if the sink is the final destination
            if self.location_index == len(self.path_ids) - 1:
                self.removed_at_step = self.model.schedule.steps
                self.location.remove(self)
                return

        elif isinstance(next_infra, Bridge):
            alternative_bridges = [next_infra]

            while self.location_index + 1 < len(self.path_ids):
                next_infra_neighbor = self.model.schedule._agents[self.path_ids[self.location_index + 1]]

                if isinstance(next_infra_neighbor, Bridge) and self.bridges_are_interchangeable(next_infra, next_infra_neighbor):
                    alternative_bridges.append(next_infra_neighbor)
                    self.location_index += 1
                    next_infra = next_infra_neighbor
                else:
                    break
            
            best_bridge = alternative_bridges[0]
            best_delay = best_bridge.get_delay_time()
            best_time = best_delay + (best_bridge.length / Vehicle.speed * Vehicle.step_time)

            for bridge in alternative_bridges[1:]:
                delay = bridge.get_delay_time()
                time = delay + (bridge.length / Vehicle.speed * Vehicle.step_time)

                if time < best_time:
                    best_bridge = bridge
                    best_delay = delay
                    best_time = time

            self.waiting_time = best_delay
            next_infra = best_bridge

            if self.waiting_time > 0:
                self.delay_time += self.waiting_time
                self.arrive_at_next(next_infra, 0)
                self.state = Vehicle.State.WAIT
                return

        # Move through zero-length nodes (cross-road intersection edges)
        if next_infra.length <= 0:
            self.arrive_at_next(next_infra, 0)
            self.drive_to_next(distance)
        elif next_infra.length > distance:
            self.arrive_at_next(next_infra, distance)
        else:
            self.drive_to_next(distance - next_infra.length)

    def arrive_at_next(self, next_infra, location_offset):
        """
        Arrive at next_infra with the given location_offset
        """
        self.location.vehicle_count -= 1
        self.location = next_infra
        self.location_offset = location_offset
        self.location.vehicle_count += 1

    def bridges_are_interchangeable(self, bridge1, bridge2, tolerance=0.00005):
        """
        Check if two bridges are interchangeable for the vehicle, 
        which means they are appriximately at the same location 
        and thus both go to the same destination point.
        """
        bridge_lat_diff = abs(bridge1.lat - bridge2.lat)
        bridge_lon_diff = abs(bridge1.lon - bridge2.lon)
        return bridge_lat_diff < tolerance and bridge_lon_diff < tolerance

# EOF -----------------------------------------------------------
