from mesa import Agent
from enum import Enum

# ---------------------------------------------------------------
class Infra(Agent):
    """
    Base class for all infrastructure components

    Attributes
    __________
    vehicle_count : int
        the number of vehicles that are currently in/on (or totally generated/removed by)
        this infrastructure component

    length : float
        the length in meters
    ...

    """

    def __init__(self, unique_id, model, length=0,
                 name='Unknown', road_name='Unknown'):
        super().__init__(unique_id, model)
        self.length = length
        self.name = name
        self.road_name = road_name
        self.vehicle_count = 0

    def step(self):
        pass

    def __str__(self):
        return type(self).__name__ + str(self.unique_id)


# ---------------------------------------------------------------
BREAKDOWN_RATES = {
    0: {'A': 0.00, 'B': 0.00, 'C': 0.00, 'D': 0.00},
    1: {'A': 0.00, 'B': 0.00, 'C': 0.00, 'D': 0.05},
    2: {'A': 0.00, 'B': 0.00, 'C': 0.05, 'D': 0.10},
    3: {'A': 0.00, 'B': 0.05, 'C': 0.10, 'D': 0.20},
    4: {'A': 0.05, 'B': 0.10, 'C': 0.20, 'D': 0.40},
}


# ---------------------------------------------------------------
class Bridge(Infra):
    """
    Creates delay time

    Attributes
    __________
    condition:
        condition of the bridge

    delay_time: int
        the delay (in ticks) caused by this bridge
    ...

    """

    def __init__(self, unique_id, model, length=0,
                 name='Unknown', road_name='Unknown', condition='Unknown'):
        super().__init__(unique_id, model, length, name, road_name)
        self.condition = condition
        self.broken = False

        scenario = getattr(self.model, 'scenario', 0)
        rates = BREAKDOWN_RATES.get(scenario, BREAKDOWN_RATES[0])

        cond = str(self.condition).strip().upper()
        if cond not in rates:
            cond = 'A'

        if self.random.random() < rates[cond]:
            self.broken = True

    def get_delay_time(self):
        if not self.broken:
            return 0

        length_m = self.length
        if length_m > 200:
            return int(self.random.triangular(60, 120, 240))
        elif length_m > 50:
            return int(self.random.uniform(45, 90))
        elif length_m > 10:
            return int(self.random.uniform(15, 60))
        else:
            return int(self.random.uniform(10, 20))


# ---------------------------------------------------------------
class Link(Infra):
    pass


# ---------------------------------------------------------------
class Intersection(Infra):
    pass


# ---------------------------------------------------------------
class Sink(Infra):
    """
    Sink removes vehicles

    Attributes
    __________
    vehicle_removed_toggle: bool
        toggles each time when a vehicle is removed
    ...

    """
    vehicle_removed_toggle = False

    def remove(self, vehicle):
        vehicle.removed_at_step = self.model.schedule.steps
        # Record travel time before removing from schedule
        self.model.travel_times.append({
            'vehicle_id': str(vehicle.unique_id),
            'generated_at_step': vehicle.generated_at_step,
            'removed_at_step': vehicle.removed_at_step,
            'travel_time_min': vehicle.removed_at_step - vehicle.generated_at_step,
            'generated_by': str(vehicle.generated_by),
        })
        self.model.schedule.remove(vehicle)
        self.vehicle_removed_toggle = not self.vehicle_removed_toggle
        # print(str(self) + ' REMOVE ' + str(vehicle))


# ---------------------------------------------------------------
class Source(Infra):
    """
    Source generates vehicles

    Class Attributes:
    -----------------
    truck_counter : int
        the number of trucks generated by ALL sources. Used as Truck ID!

    Attributes
    __________
    generation_frequency: int
        the frequency (the number of ticks) by which a truck is generated

    vehicle_generated_flag: bool
        True when a Truck is generated in this tick; False otherwise
    ...

    """

    truck_counter = 0
    generation_frequency = 5
    vehicle_generated_flag = False

    def step(self):
        if self.model.schedule.steps % self.generation_frequency == 0:
            self.generate_truck()
        else:
            self.vehicle_generated_flag = False

    def generate_truck(self):
        """
        Generates a truck, sets its path, increases the global and local counters
        """
        try:
            agent = Vehicle('Truck' + str(Source.truck_counter), self.model, self)
            if agent:
                self.model.schedule.add(agent)
                agent.set_path()
                if agent.path_ids is None or len(agent.path_ids) == 0:
                    print(f"WARNING: {self} has no valid path, removing truck.")
                    self.model.schedule.remove(agent)
                    return
                Source.truck_counter += 1
                self.vehicle_count += 1
                self.vehicle_generated_flag = True
                # print(str(self) + " GENERATE " + str(agent))
        except Exception as e:
            print("Oops!", e.__class__, e, "occurred.")


# ---------------------------------------------------------------
class SourceSink(Source, Sink):
    """
    Generates and removes trucks
    """
    pass


# ---------------------------------------------------------------
class Vehicle(Agent):
    """

    Attributes
    __________
    speed: float
        speed in meter per minute (m/min)

    step_time: int
        the number of minutes (or seconds) a tick represents
        Used as a base to change unites

    state: Enum (DRIVE | WAIT)
        state of the vehicle

    location: Infra
        reference to the Infra where the vehicle is located

    location_offset: float
        the location offset in meters relative to the starting point of
        the Infra, which has a certain length
        i.e. location_offset < length

    path_ids: Series
        the whole path (origin and destination) where the vehicle shall drive
        It consists the Infras' uniques IDs in a sequential order

    location_index: int
        a pointer to the current Infra in "path_ids" (above)
        i.e. the id of self.location is self.path_ids[self.location_index]

    waiting_time: int
        the time the vehicle needs to wait

    generated_at_step: int
        the timestamp (number of ticks) that the vehicle is generated

    removed_at_step: int
        the timestamp (number of ticks) that the vehicle is removed
    ...

    """

    # 48 km/h translated into meter per min
    speed = 48 * 1000 / 60
    # One tick represents 1 minute
    step_time = 1

    class State(Enum):
        DRIVE = 1
        WAIT = 2

    def __init__(self, unique_id, model, generated_by,
                 location_offset=0, path_ids=None):
        super().__init__(unique_id, model)
        self.generated_by = generated_by
        self.generated_at_step = model.schedule.steps
        self.location = generated_by
        self.location_offset = location_offset
        self.pos = generated_by.pos
        self.path_ids = path_ids
        # default values
        self.state = Vehicle.State.DRIVE
        self.location_index = 0
        self.waiting_time = 0
        self.waited_at = None
        self.removed_at_step = None

    def __str__(self):
        return "Vehicle" + str(self.unique_id) + \
               " +" + str(self.generated_at_step) + " -" + str(self.removed_at_step) + \
               " " + str(self.state) + '(' + str(self.waiting_time) + ') ' + \
               str(self.location) + '(' + str(self.location.vehicle_count) + ') ' + str(self.location_offset)

    def set_path(self):
        """
        Set the origin destination path of the vehicle
        """
        self.path_ids = self.model.get_route(self.generated_by.unique_id)

    def step(self):
        """
        Vehicle waits or drives at each step
        """
        if self.state == Vehicle.State.WAIT:
            self.waiting_time = max(self.waiting_time - 1, 0)
            if self.waiting_time == 0:
                self.waited_at = self.location
                self.state = Vehicle.State.DRIVE

        if self.state == Vehicle.State.DRIVE:
            self.drive()

        # print(self)

    def drive(self):
        # the distance that vehicle drives in a tick
        distance = Vehicle.speed * Vehicle.step_time
        distance_rest = self.location_offset + distance - self.location.length

        if distance_rest > 0:
            self.drive_to_next(distance_rest)
        else:
            self.location_offset += distance

    def drive_to_next(self, distance):
        """
        vehicle shall move to the next object with the given distance
        """
        self.location_index += 1

        if self.location_index >= len(self.path_ids):
            print(f"WARNING: {self} reached end of path without a Sink. Removing.")
            self.removed_at_step = self.model.schedule.steps
            self.location.vehicle_count -= 1
            self.model.schedule.remove(self)
            return

        next_id = self.path_ids[self.location_index]
        next_infra = self.model.schedule._agents.get(next_id, None)

        if next_infra is None:
            print(f"ERROR: Agent {next_id} not found in schedule! Removing vehicle.")
            self.removed_at_step = self.model.schedule.steps
            self.location.vehicle_count -= 1
            self.model.schedule.remove(self)
            return

        if isinstance(next_infra, Sink):
            self.arrive_at_next(next_infra, 0)

            # Check if the sink is the final destination
            if self.location_index == len(self.path_ids) - 1:
                self.removed_at_step = self.model.schedule.steps
                self.location.remove(self)
                return

        elif isinstance(next_infra, Bridge):
            self.waiting_time = next_infra.get_delay_time()
            if self.waiting_time > 0:
                self.arrive_at_next(next_infra, 0)
                self.state = Vehicle.State.WAIT
                return

        # Move through zero-length nodes (cross-road intersection edges)
        if next_infra.length <= 0:
            self.arrive_at_next(next_infra, 0)
            self.drive_to_next(distance)
        elif next_infra.length > distance:
            self.arrive_at_next(next_infra, distance)
        else:
            self.drive_to_next(distance - next_infra.length)

    def arrive_at_next(self, next_infra, location_offset):
        """
        Arrive at next_infra with the given location_offset
        """
        self.location.vehicle_count -= 1
        self.location = next_infra
        self.location_offset = location_offset
        self.location.vehicle_count += 1

# EOF -----------------------------------------------------------
